export const COMPONENT_CODES = [
  "Değer Zinciri Analizi Çalışmaları",
  "Diğer Fon Kaynaklarına Proje Yazılmasının Özendirilmesi ve Teknik Yardım Masası Faaliyetleri",
  "Kayseri Tarıma Dayalı Sera İhtisas Organize Tarım Bölgesi ve Yerköy Tarıma Dayalı İhtisas OSB  İş Birliği ve Yenilikçi Uygulamalar",
  "Sınai Mülkiyet Hakları Faaliyetleri",
  "Anadoludakiler/Yerel Ürünleri Ticarileştirme Teması ve “Anadoludakiler” Projesi Çalışmaları",
  "Yöresel Ürünlerin Tanıtımı ve Pazarlanması",
  "Kırsal ve Sosyal Kalkınma Kapasite Geliştirme Programı",
  "“Anadoludakiler” Projesine Katkı Sağlayıcı Coğrafi İşaretli Ürün Geliştirme Programı",
  "Yöresel Ürün Tespit Çalışması",
  "Sürdürülebilir Kooperatifler ve Kadın Girişimciliğinin Geliştirilmesi Programı",
  "Bölge Tanıtımı ve Ortak Paydaş Faaliyetleri",
  "Sosyal Gelişmeyi Destekleme Programı",
  "Çalışan ve Üreten Gençler Programı",
  "TR72 Bölgesi Mesleki ve Teknolojik Eğitim Altyapısını Geliştirme Güdümlü Projesi",
  "Kırsal Sosyal Kalkınma Skala Proje Desteği",
  "Kırsal Kalkınma Teknik Destek Programı",
  "TR72 Makine İmalat Sektörü Değer Zinciri Analizi",
  "Bölgesel İş Gücü ve Mesleki Yeterlilik Analizi Çalışmaları",
  "TR72 Bölgesi İmalat Sanayi Teknik Destek Programları Etki Analizi",
  "TR72 Bölgesi İmalat Sanayi Nitelikli Raporlarının Güncellenmesi",
  "TR72 İmalat Sanayinde Yeni Yatırım Alanları ve Teknoloji Odaklı Fizibilite Çalışmaları",
  "İklim Risklerine Karşı Sanayi Tabanlı Uyum Stratejisi Geliştirilmesi",
  "İhracat Analiz Raporları",
  "Döngüsel Sanayi Heckathonu Düzenlenmesi",
  "Bölgedeki Yerel Ürünlerin Ticarileştirilmesi ve Seri Üretimi İçin Geliştirme Programı",
  "Bölge İmalat Sanayi İle İlişkili Paydaşlarla SOP Özel Amaçlarına Yönelik Ortak Faaliyetler Düzenlenmesi",
  "TR72 Ar-Ge ve Tasarım Merkezleri Tanıtım Günü",
  "Kuzey-Güney Sanayi Koridorunda TR72 Bölgesi’nin Rolü Çalışması",
  "TR72 Sanayi İşletmelerinde Sürdürülebilirlik Yönetimi ve Yeşil Uyum Çalışmaları",
  "Yaşam Döngüsü Değerlendirmesi (LCA) Eğitimleri",
  "Yeşil Dönüşüm Temelli Endüstriyel Simbiyoz Eğitimleri",
  "TR72 İmalat Sanayine Yönelik Merkezi Hibe Programlarının Tanıtımı",
  "Üreten Şehirler Programı Çalışmaları",
  "Silikon Fotonik Çip-Üstü LIDAR (Lazer İle Görüntü Tespiti Ve Uzaklık Belirleme Sistemi) Üretimi Projesi (CMDP)",
  "Sogreen Projeleri",
  "TR72 İmalat Sanayi Teknik Destek Programı",
  "TR72 İmalat Sanayi Dijitalleşme ve E-Ticaret Kapasite Geliştirme Programı",
  "TR72 Bölgesi Turizm Potansiyeli Mevcut Durum Analizi",
  "Ark Of Taste Çalışmaları",
  "Sağlık Turizmi İşbirliği Buluşması",
  "Aydıncık İlçesi 2026 UNWTO Best Tourism Villages Başvurusu",
  "UNESCO “Öğrenen Şehirler Ağı” Üyelik Faaliyetleri",
  "Turizm İşletmeleri Kapasite Geliştirme Programı",
  "Sarıkaya Turizm Çalıştayı",
  "Bölgenin Turizm Değerlerinin Tanıtımı",
  "Buruciye'de Usta Sesleri Yükseliyor Güdümlü Projesi (CMDP)",
  "Akdağmadeni Kırsal Turizm Güdümlü Projesi",
  "Alternatif Turizm Güdümlü Proje Geliştirme Faaliyetleri",
  "2026 Yılı Orta Anadolu’yu Keşfet Alternatif Mali Destek Programı",
  "2026 Teknik Destek Programı",
  "Ajansın İnsan Kaynakları Kapasitesinin Geliştirilmesi",
  "Ajans Fiziki ve Teknik Altyapısının İyileştirilmesi Hedefi Kapsamındaki Faaliyetler",
  "Tüketime Yönelik Mal ve Malzeme Alımları",
  "Yolluklar",
  "Görev Giderleri",
  "Hizmet Alımları",
  "Temsil ve Tanıtma Giderleri",
  "Menkul Mal, Gayrimaddi Hak Alım, Bakım ve Onarım Giderleri",
  "Gayrimenkul Mal Bakım ve Onarım Giderleri",
  "Teknik Destek Giderleri",
  "Mamul Mal Alımları",
  "Kurumsal İletişim ve Raporlama Faaliyetleri",
  "Personel Ücretleri",
  "İhbar ve Kıdem Tazminatları",
  "Sosyal Haklar",
  "Fazla Mesailer",
  "Ödül ve İkramiyeler",
  "Ek Çalışma Karşılıkları",
  "Diğer Ödemeler",
  "İşsizlik Sigortası Fonuna Ödemeler",
  "Sosyal Güvenlik Kurumuna Ödemeler",
  "Çalıştaylar, Araştırma Raporları ve Bilgi Notları",
  "İlçe Gelişim Planı Raporlarının Revizyonu ve İlçe Tanıtım Ziyaretleri",
  "Yatırım Alanları Kitapçıklarının Tanıtımı",
  "Firma Ziyaretleri ve Potansiyel Yatırım Konuları Araştırması",
  "Girişimcilik Faaliyetleri",
  "81 İl 81 Ürün Programı Faaliyetleri",
  "Yerel Kalkınma Hamlesi Programı",
  "Türkiye Siber Vatan Programı",
  "Bölge Kalkınma İdareleri ve Diğer Ajanslar ile İşbirliği",
  "Yürütme ve İcra Kurulu Faaliyetleri",
  "Uluslararası Yatırım Çekme ve İşbirliği Bağlantılarının Kurulması, Yurtdışı Pazar Araştırmaları",
  "Üniversite – Sanayi İşbirliği Faaliyetleri",
  "Ekonomi Bülteni Çalışmaları",
  "CMDP Proje Geliştirme Faaliyetleri ve Uluslararası Program ve Fon Kaynaklarına Başvuru Yapılması",
  "Şirket Değerleme Uygulamalı Eğitimi",
  "Yatırım Altyapısının Güçlendirilmesine Yönelik Çalışmalar",
  "Dış Ticaret Masası",
  "Yurtiçi ve Yurtdışı Fuar ve Çalışma Ziyaretleri",
  "İş İnsanı Buluşmaları",
  "KOP Proje Uygulamaları"
];
